#!/usr/bin/env node
// Bridge Synclair's product-knowledge skills into the host repo so every agent
// tool auto-surfaces them — Claude Code (.claude/skills), Codex (.agents/skills),
// and Cursor (.cursor/skills). Embedded / co-located mode only.
//
// The problem it solves: engineers open the HOST repo at its root, but Synclair's
// skills live in the co-located synclair/ subdir — a directory agent tools don't
// scan. Without this, none of the product knowledge auto-surfaces for anyone.
//
// Why copies, not symlinks: a mixed-OS team mangles symlinks on Windows checkouts.
// Canonical source stays in <synclair>/.claude/skills/; these are regenerated
// copies. Re-run to refresh; `--check` fails on drift (safe to add to verify-ui —
// it no-ops in a non-embedded repo like the Synclair mother repo itself).
//
//   node scripts/bridge-agents.mjs           # write/refresh the doorways
//   node scripts/bridge-agents.mjs --check    # CI: fail if a copy drifted
//
// Which skills reach the host as full copies: those whose SKILL.md frontmatter
// sets `ambient: true` — the knowledge-CONSUMPTION + host-safe build-guidance
// skills an engineer building in the product app reads (e.g. product-spec,
// project-identity, building-in-this-repo). Knowledge-PRODUCTION (figma-distiller,
// product-summary) and hub build-MECHANICS (build-view, component-library) are NOT
// copied — they assume Synclair's own app structure — but they ARE advertised as
// pointers in the AGENTS.md block (see POINTER_SKILLS), so every agent knows the
// full capability surface exists in the hub even when the full text isn't bridged.
// Falls back to a default set if no skill is flagged.

import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync, cpSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_BRIDGE_SKILLS = ["product-spec", "project-identity"];
const DOORWAYS = [".claude/skills", ".agents/skills", ".cursor/skills"];

// Subagents reach the host root the same way skills do, opting in with the same
// `ambient: true` frontmatter flag — so the decision stays on each capability
// rather than in a list here that drifts as agents are added.
//
// Why this exists: agent tools discover subagents from `.claude/agents` at the
// SESSION root. Synclair's live in the co-located subdir, so from the host root
// they were invisible — `component-cataloger` and the rest could not be invoked
// at all, even though the AGENTS.md block said "invoke them by name". Flag the
// HOST-FACING ones (the diggers that read the host repo); hub-facing reviewers
// that assume Synclair's own structure stay unflagged and unbridged.
//
// One doorway, not three: `.claude/agents` is the only subagent directory
// convention that is real today. Inventing `.agents/agents` / `.cursor/agents`
// would scatter copies nothing reads.
const AGENT_DOORWAYS = [".claude/agents"];

// Deeper capabilities that stay in the hub (too app-structure-specific to copy),
// but are advertised in the AGENTS.md doorway so every agent knows they exist and
// where to read them. Curated, not auto-derived — keep it short and high-signal.
const POINTER_SKILLS = [
  ["build-view", "build/extend a screen from requirements + Figma"],
  ["component-library", "invent/register a reusable component (the invention gate)"],
  ["figma-distiller", "distill a Figma file into a build-ready design digest"],
  ["pages-map", "map the app's routes/views"],
  ["codebase-map", "map the backend/architecture"],
];

const MARK_START = "<!-- synclair:bridge:start (generated by scripts/bridge-agents.mjs — do not edit by hand) -->";
const MARK_END = "<!-- synclair:bridge:end -->";
// Match any existing bridge block by its stable tokens, so a marker-text change
// replaces the old block instead of appending a duplicate.
const BLOCK_RE = /<!-- synclair:bridge:start[\s\S]*?<!-- synclair:bridge:end -->/;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const synclairRoot = dirname(scriptDir);
const skillsDir = join(synclairRoot, ".claude", "skills");
const agentsDir = join(synclairRoot, ".claude", "agents");
const check = process.argv.includes("--check");

// --- topology: only bridge when co-located inside a host repo ----------------
function setupMode() {
  const p = join(synclairRoot, "data", "setup.json");
  if (existsSync(p)) { try { return JSON.parse(readFileSync(p, "utf8")).mode ?? null; } catch { /* blank */ } }
  return null;
}

// --- select skills flagged `ambient: true` (fallback: the default set) --------
function frontmatter(text) { const m = text.match(/^---\n([\s\S]*?)\n---/); return m ? m[1] : ""; }
function selectSkills() {
  const flagged = [];
  for (const name of readdirSync(skillsDir)) {
    const f = join(skillsDir, name, "SKILL.md");
    if (existsSync(f) && /(^|\n)ambient:\s*true\s*(\n|$)/.test(frontmatter(readFileSync(f, "utf8")))) flagged.push(name);
  }
  return flagged.length ? flagged.sort() : DEFAULT_BRIDGE_SKILLS;
}

/** Agents flagged `ambient: true`. Empty is legitimate — bridge nothing. */
function selectAgents() {
  if (!existsSync(agentsDir)) return [];
  return readdirSync(agentsDir)
    .filter((f) => f.endsWith(".md"))
    .filter((f) => /(^|\n)ambient:\s*true\s*(\n|$)/.test(frontmatter(readFileSync(join(agentsDir, f), "utf8"))))
    .sort();
}

function walk(dir, base = dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, base, out);
    else out.push(relative(base, full));
  }
  return out;
}

// --- AGENTS.md router block (what Codex/Cursor read; Claude gets it via import) ---
function agentsBlock(skills, agents = []) {
  // Only advertise pointer skills that actually exist in the hub, so a renamed
  // or removed skill never leaves a dead pointer in the doorway.
  const pointers = POINTER_SKILLS.filter(([s]) => existsSync(join(skillsDir, s, "SKILL.md")));
  const lines = skills.map((s) => {
    const f = join(skillsDir, s, "SKILL.md");
    const desc = (frontmatter(existsSync(f) ? readFileSync(f, "utf8") : "").match(/(^|\n)description:\s*(.+)/)?.[2] || "")
      .replace(/\s+/g, " ").trim();
    const short = desc.split(/[—.]/)[0].trim();
    return `- **${s}** — ${short || s}.`;
  });
  return [
    MARK_START,
    "## Product knowledge (Synclair)",
    "",
    "This repo ships distilled product knowledge as skills, auto-loaded by",
    "**Claude Code** (`.claude/skills`), **Codex** (`.agents/skills`), and",
    "**Cursor** (`.cursor/skills`). When a task matches, read the skill:",
    "",
    ...lines,
    "",
    ...(pointers.length
      ? [
          "Deeper build & knowledge skills stay in the hub (they assume Synclair's own",
          "structure) — read them in `synclair/.claude/skills/` when the task fits:",
          "",
          ...pointers.map(([s, why]) => `- **${s}** — ${why}.`),
          "",
        ]
      : []),
    ...(agents.length
      ? [
          "Specialist SUBAGENTS bridged to this root — invoke them by name:",
          "",
          ...agents.map((f) => `- **${f.replace(/\.md$/, "")}**`),
          "",
          "The rest (reviewers, tier-arbiter, visual validator) assume Synclair's own",
          "structure and stay in `synclair/.claude/agents/` — run them from there.",
          "",
        ]
      : [
          "Specialist agents (diggers, cataloger, tier-arbiter, reviewers, visual",
          "validator) live in `synclair/.claude/agents/`. NOTE: agent tools only",
          "discover subagents at the session root, so from here they are not",
          "invokable by name — `cd synclair` first, or flag one `ambient: true`",
          "and re-run the bridge.",
          "",
        ]),
    "The full hub (component catalog, system map, design tokens) is the co-located",
    "app: `cd synclair && npm run dev` → http://localhost:4100/synclair.",
    "",
    // The registration alone doesn't get used — an agent reaches for whole
    // files unless told the tools answer the same question for a fraction of
    // the context. This block is the one place all three clients read.
    "### Ask Synclair, don't read its files",
    "",
    "A `synclair` MCP server exposes the catalog, sitemap, tokens, system map and",
    "knowledge as task-shaped tools — `get_overview`, `search_library`,",
    "`get_component`, `get_foundation`, `get_page`, `get_system`, `get_knowledge`.",
    "**Prefer them over reading `synclair/data/*.json` or `registry.json`**: the",
    "same answers cost ~92% fewer tokens, and each one reports whether the data",
    "is still fresh. It needs no dev server.",
    "",
    // "Not offering those tools?" asked the reader to notice an ABSENCE, which
    // is the one thing an agent reliably fails to do — it has no way to miss a
    // tool that was never offered. The generated status block in this file now
    // STATES whether the server is registered, so this line only has to say
    // what to run. `check:mcp` answers the half `mcp:install` cannot: whether a
    // session launched from a given directory would actually find it.
    "Register once: `cd synclair && npm run mcp:install`, then `npm run check:mcp`",
    "to confirm it is reachable from where you start sessions (Claude Code + Cursor",
    "are committed; add `-- --user` for sessions that start outside this repo, and",
    "`-- --codex` for Codex).",
    "",
    "_Canonical source: `synclair/.claude/skills/`. These doorway copies are",
    "regenerated by `node synclair/scripts/bridge-agents.mjs` — do not hand-edit._",
    MARK_END,
  ].join("\n");
}

function upsertAgentsBlock(hostRoot, block) {
  const path = join(hostRoot, "AGENTS.md");
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const current = existing.match(BLOCK_RE)?.[0] ?? null;
  if (check) { if (current !== block) { console.error("✗ AGENTS.md product-knowledge block is missing or stale."); return false; } return true; }
  const next = current !== null
    ? existing.replace(BLOCK_RE, block)
    : (existing.trimEnd() + "\n\n" + block + "\n").replace(/^\n+/, "");
  if (next !== existing) writeFileSync(path, next);
  return true;
}

// --- main --------------------------------------------------------------------
const mode = setupMode();
if (mode !== "embedded") {
  if (check) { console.log(`· agent bridge: not embedded (mode: ${mode ?? "unresolved"}) — nothing to check.`); process.exit(0); }
  console.error(
    `✗ setup mode is ${mode === null ? "unresolved" : `"${mode}"`}, not "embedded".\n` +
    `  This bridge only applies when Synclair is co-located inside a host repo.`
  );
  process.exit(1);
}

const hostRoot = dirname(synclairRoot);
const skills = selectSkills();
let ok = true;

for (const name of skills) {
  const src = join(skillsDir, name);
  if (!existsSync(src)) { console.error(`✗ skill "${name}" not found — nothing to bridge.`); process.exit(1); }
  const files = walk(src);
  for (const doorway of DOORWAYS) {
    const dest = join(hostRoot, doorway, name);
    if (check) {
      const drift = !existsSync(dest) || files.some(
        (f) => !existsSync(join(dest, f)) || readFileSync(join(src, f), "utf8") !== readFileSync(join(dest, f), "utf8")
      );
      if (drift) { console.error(`✗ drift: ${doorway}/${name} differs from canonical.`); ok = false; }
    } else {
      rmSync(dest, { recursive: true, force: true });
      cpSync(src, dest, { recursive: true });
    }
  }
}

const agents = selectAgents();
for (const file of agents) {
  const src = join(agentsDir, file);
  const body = readFileSync(src, "utf8");
  for (const doorway of AGENT_DOORWAYS) {
    const dest = join(hostRoot, doorway, file);
    if (check) {
      if (!existsSync(dest) || readFileSync(dest, "utf8") !== body) {
        console.error(`✗ drift: ${doorway}/${file} differs from canonical.`);
        ok = false;
      }
    } else {
      mkdirSync(dirname(dest), { recursive: true });
      writeFileSync(dest, body);
    }
  }
}

// Remove doorway agents that are no longer flagged, so un-flagging an agent
// actually withdraws it instead of leaving an orphan the host still resolves.
for (const doorway of AGENT_DOORWAYS) {
  const dir = join(hostRoot, doorway);
  if (!existsSync(dir)) continue;
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".md"))) {
    if (agents.includes(file)) continue;
    if (!existsSync(join(agentsDir, file))) continue; // not ours — leave it alone
    if (check) { console.error(`✗ stale: ${doorway}/${file} is no longer flagged ambient.`); ok = false; }
    else rmSync(join(dir, file), { force: true });
  }
}

if (!upsertAgentsBlock(hostRoot, agentsBlock(skills, agents))) ok = false;

if (check) {
  if (!ok) { console.error("\nRun `node synclair/scripts/bridge-agents.mjs` to refresh the doorways."); process.exit(1); }
  console.log(`✓ agent bridge in sync (${skills.join(", ")} → .claude/.agents/.cursor).`);
  console.log(
    agents.length
      ? `✓ ${agents.length} subagent(s) in sync → ${AGENT_DOORWAYS.join(", ")}.`
      : `· no subagents flagged \`ambient: true\` — none bridged.`
  );
} else {
  console.log(`✓ bridged ${skills.join(", ")} → ${DOORWAYS.join(", ")} at the host root`);
  if (agents.length)
    console.log(
      `  + ${agents.length} subagent(s) → ${AGENT_DOORWAYS.join(", ")}: ` +
        agents.map((f) => f.replace(/\.md$/, "")).join(", ")
    );
  console.log("  + refreshed the Product knowledge block in AGENTS.md");
  console.log("  Commit the new .claude/.agents/.cursor folders + AGENTS.md so the team gets them on pull.");
}
