#!/usr/bin/env node
// Bridge Synclair's product-knowledge skills into the host repo so every agent
// tool auto-surfaces them — Claude Code (.claude/skills), Codex (.agents/skills),
// and Cursor (.cursor/skills). Embedded / co-located mode only.
//
// The problem it solves: engineers open the HOST repo at its root, but Synclair's
// skills live in the co-located synclair/ subdir — a directory agent tools don't
// scan. Without this, none of the product knowledge auto-surfaces for anyone.
//
// Why copies, not symlinks: a mixed-OS team mangles symlinks on Windows checkouts.
// Canonical source stays in <synclair>/.claude/skills/; these are regenerated
// copies. Re-run to refresh; `--check` fails on drift (safe to add to verify-ui —
// it no-ops in a non-embedded repo like the Synclair mother repo itself).
//
//   node scripts/bridge-agents.mjs           # write/refresh the doorways
//   node scripts/bridge-agents.mjs --check    # CI: fail if a copy drifted
//
// Which skills reach the host as full copies: those whose SKILL.md frontmatter
// sets `ambient: true` — the knowledge-CONSUMPTION + host-safe build-guidance
// skills an engineer building in the product app reads (e.g. product-spec,
// project-identity, building-in-this-repo). Knowledge-PRODUCTION (figma-distiller,
// product-summary) and hub build-MECHANICS (build-view, component-library) are NOT
// copied — they assume Synclair's own app structure — but they ARE advertised as
// pointers in the AGENTS.md block (see POINTER_SKILLS), so every agent knows the
// full capability surface exists in the hub even when the full text isn't bridged.
// Falls back to a default set if no skill is flagged.

import { readFileSync, writeFileSync, existsSync, rmSync, cpSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT_BRIDGE_SKILLS = ["product-spec", "project-identity"];
const DOORWAYS = [".claude/skills", ".agents/skills", ".cursor/skills"];

// Deeper capabilities that stay in the hub (too app-structure-specific to copy),
// but are advertised in the AGENTS.md doorway so every agent knows they exist and
// where to read them. Curated, not auto-derived — keep it short and high-signal.
const POINTER_SKILLS = [
  ["build-view", "build/extend a screen from requirements + Figma"],
  ["component-library", "invent/register a reusable component (the invention gate)"],
  ["figma-distiller", "distill a Figma file into a build-ready design digest"],
  ["pages-map", "map the app's routes/views"],
  ["codebase-map", "map the backend/architecture"],
];

const MARK_START = "<!-- synclair:bridge:start (generated by scripts/bridge-agents.mjs — do not edit by hand) -->";
const MARK_END = "<!-- synclair:bridge:end -->";
// Match any existing bridge block by its stable tokens, so a marker-text change
// replaces the old block instead of appending a duplicate.
const BLOCK_RE = /<!-- synclair:bridge:start[\s\S]*?<!-- synclair:bridge:end -->/;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const synclairRoot = dirname(scriptDir);
const skillsDir = join(synclairRoot, ".claude", "skills");
const check = process.argv.includes("--check");

// --- topology: only bridge when co-located inside a host repo ----------------
function setupMode() {
  const p = join(synclairRoot, "data", "setup.json");
  if (existsSync(p)) { try { return JSON.parse(readFileSync(p, "utf8")).mode ?? null; } catch { /* blank */ } }
  return null;
}

// --- select skills flagged `ambient: true` (fallback: the default set) --------
function frontmatter(text) { const m = text.match(/^---\n([\s\S]*?)\n---/); return m ? m[1] : ""; }
function selectSkills() {
  const flagged = [];
  for (const name of readdirSync(skillsDir)) {
    const f = join(skillsDir, name, "SKILL.md");
    if (existsSync(f) && /(^|\n)ambient:\s*true\s*(\n|$)/.test(frontmatter(readFileSync(f, "utf8")))) flagged.push(name);
  }
  return flagged.length ? flagged.sort() : DEFAULT_BRIDGE_SKILLS;
}

function walk(dir, base = dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, base, out);
    else out.push(relative(base, full));
  }
  return out;
}

// --- AGENTS.md router block (what Codex/Cursor read; Claude gets it via import) ---
function agentsBlock(skills) {
  // Only advertise pointer skills that actually exist in the hub, so a renamed
  // or removed skill never leaves a dead pointer in the doorway.
  const pointers = POINTER_SKILLS.filter(([s]) => existsSync(join(skillsDir, s, "SKILL.md")));
  const lines = skills.map((s) => {
    const f = join(skillsDir, s, "SKILL.md");
    const desc = (frontmatter(existsSync(f) ? readFileSync(f, "utf8") : "").match(/(^|\n)description:\s*(.+)/)?.[2] || "")
      .replace(/\s+/g, " ").trim();
    const short = desc.split(/[—.]/)[0].trim();
    return `- **${s}** — ${short || s}.`;
  });
  return [
    MARK_START,
    "## Product knowledge (Synclair)",
    "",
    "This repo ships distilled product knowledge as skills, auto-loaded by",
    "**Claude Code** (`.claude/skills`), **Codex** (`.agents/skills`), and",
    "**Cursor** (`.cursor/skills`). When a task matches, read the skill:",
    "",
    ...lines,
    "",
    ...(pointers.length
      ? [
          "Deeper build & knowledge skills stay in the hub (they assume Synclair's own",
          "structure) — read them in `synclair/.claude/skills/` when the task fits:",
          "",
          ...pointers.map(([s, why]) => `- **${s}** — ${why}.`),
          "",
        ]
      : []),
    "Specialist agents (diggers, cataloger, tier-arbiter, reviewers, visual",
    "validator) live in `synclair/.claude/agents/` — invoke them by name.",
    "",
    "The full hub (component catalog, system map, design tokens) is the co-located",
    "app: `cd synclair && npm run dev` → http://localhost:4100/synclair.",
    "",
    "_Canonical source: `synclair/.claude/skills/`. These doorway copies are",
    "regenerated by `node synclair/scripts/bridge-agents.mjs` — do not hand-edit._",
    MARK_END,
  ].join("\n");
}

function upsertAgentsBlock(hostRoot, block) {
  const path = join(hostRoot, "AGENTS.md");
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const current = existing.match(BLOCK_RE)?.[0] ?? null;
  if (check) { if (current !== block) { console.error("✗ AGENTS.md product-knowledge block is missing or stale."); return false; } return true; }
  const next = current !== null
    ? existing.replace(BLOCK_RE, block)
    : (existing.trimEnd() + "\n\n" + block + "\n").replace(/^\n+/, "");
  if (next !== existing) writeFileSync(path, next);
  return true;
}

// --- main --------------------------------------------------------------------
const mode = setupMode();
if (mode !== "embedded") {
  if (check) { console.log(`· agent bridge: not embedded (mode: ${mode ?? "unresolved"}) — nothing to check.`); process.exit(0); }
  console.error(
    `✗ setup mode is ${mode === null ? "unresolved" : `"${mode}"`}, not "embedded".\n` +
    `  This bridge only applies when Synclair is co-located inside a host repo.`
  );
  process.exit(1);
}

const hostRoot = dirname(synclairRoot);
const skills = selectSkills();
let ok = true;

for (const name of skills) {
  const src = join(skillsDir, name);
  if (!existsSync(src)) { console.error(`✗ skill "${name}" not found — nothing to bridge.`); process.exit(1); }
  const files = walk(src);
  for (const doorway of DOORWAYS) {
    const dest = join(hostRoot, doorway, name);
    if (check) {
      const drift = !existsSync(dest) || files.some(
        (f) => !existsSync(join(dest, f)) || readFileSync(join(src, f), "utf8") !== readFileSync(join(dest, f), "utf8")
      );
      if (drift) { console.error(`✗ drift: ${doorway}/${name} differs from canonical.`); ok = false; }
    } else {
      rmSync(dest, { recursive: true, force: true });
      cpSync(src, dest, { recursive: true });
    }
  }
}

if (!upsertAgentsBlock(hostRoot, agentsBlock(skills))) ok = false;

if (check) {
  if (!ok) { console.error("\nRun `node synclair/scripts/bridge-agents.mjs` to refresh the doorways."); process.exit(1); }
  console.log(`✓ agent bridge in sync (${skills.join(", ")} → .claude/.agents/.cursor).`);
} else {
  console.log(`✓ bridged ${skills.join(", ")} → ${DOORWAYS.join(", ")} at the host root`);
  console.log("  + refreshed the Product knowledge block in AGENTS.md");
  console.log("  Commit the new .claude/.agents/.cursor folders + AGENTS.md so the team gets them on pull.");
}
